Repository zabavb/Libro, pull requests merged in 2024-12, with the labels that each got.

#53 Created file CODEOWNERS where sign myself as admin.
  .github/CODEOWNERS
Labels: enhancement, wontfix

#58 Feature/backend/library-entities/order-entities
  Library/OrderEntities/DeliveryType.cs
  OrderApi/Data/DataSeeder.cs
Labels: enhancement

#57 Created project UserAPI
  UserAPI/Program.cs
  UserAPI/Properties/launchSettings.json
  UserAPI/UserAPI.csproj
  UserAPI/UserAPI.http
  UserAPI/appsettings.Development.json
  UserAPI/appsettings.json
  book-store.sln
Labels: enhancement

#63 Feature/backend/library-entities/order-entities
  Library/OrderEntities/Order.cs
  Library/OrderEntities/OrderStatus.cs
Labels: enhancement

#62 Feature/backend/book api/other controllers
  BookApi/Controllers/AuthorsController.cs
  BookApi/Controllers/CategoriesController.cs
  BookApi/Models/Author.cs
  BookApi/Profiles/AuthorProfile.cs
  BookApi/Profiles/CategoryProfile.cs
  BookApi/Program.cs
  BookApi/Services/AuthorService.cs
  BookApi/Services/CategoryService.cs
  BookApi/Services/IAuthorService.cs
  BookApi/Services/ICategoryService.cs
Labels: enhancement

#64 Feature/backend/order api/orderUpdate
  OrderApi/Data/DataSeeder.cs
  OrderApi/Models/Order.cs
  OrderApi/Services/OrderService.cs
Labels: enhancement

#66 Feature/backend/order api/entities
  UserAPI/Data/Configurations/PasswordConfiguration.cs
  UserAPI/Data/Configurations/SubscriptionConfiguration.cs
  UserAPI/Data/Configurations/UserConfiguration.cs
  UserAPI/Data/UserDbContext.cs
  UserAPI/GlobalUsings.cs
  UserAPI/Models/Password.cs
  UserAPI/Models/User.cs
  UserAPI/UserAPI.csproj
Labels: enhancement

#67 Feature/backend/library/user entities #2
  Library/UserEntities/Password.cs
  Library/UserEntities/Subscription.cs
  Library/UserEntities/User.cs
Labels: enhancement

#72 Fix/backend/order/entities
  Library/UserEntities/Password.cs
  Library/UserEntities/Subscription.cs
  Library/UserEntities/User.cs
  UserAPI/GlobalUsings.cs
  UserAPI/Models/Password.cs
  UserAPI/Models/Subscription.cs
  UserAPI/Models/User.cs
Labels: enhancement

#74 Feature/backend/library/order-entities/validation
  Library/OrderEntities/Order.cs
  Library/Validators/EnumRangeAttribute.cs
  OrderApi/OrderApi.csproj
  book-store.sln
Labels: enhancement

#76 Temporary remove Regex cuz of issues with service development
  Library/OrderEntities/Order.cs
Labels: bug

#92 Feature/backend/order-api/repository
  OrderApi/Program.cs
  OrderApi/Repository/IRepository/IOrderRepository.cs
  OrderApi/Repository/OrderRepository.cs
  OrderApi/Services/OrderService.cs
Labels: enhancement

#99 Feature/backend/user api/crud operations
  UserAPI/Abstractions/IManager.cs
  UserAPI/Controllers/UsersController.cs
  UserAPI/Data/Configurations/SubscriptionConfiguration.cs
  UserAPI/Data/Configurations/UserConfiguration.cs
  UserAPI/GlobalUsings.cs
  UserAPI/Models/DTOs/SubscriptionDTO.cs
  UserAPI/Models/DTOs/UserDTO.cs
  UserAPI/Models/PaginatedResult.cs
  UserAPI/Models/Password.cs
  UserAPI/Models/User.cs
  UserAPI/Profiles/SubscriptionProfile.cs
  UserAPI/Profiles/UserProfile.cs
  UserAPI/Program.cs
  UserAPI/Repositories/SubscriptionRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/Services/SubscriptionService.cs
  UserAPI/Services/UserService.cs
  UserAPI/UserAPI.csproj
  UserAPI/appsettings.json
Labels: enhancement

#102 Feature/backend/user api/replace validation with db relationships
  Library/UserEntities/Password.cs
  Library/UserEntities/RoleType.cs
  Library/UserEntities/Subscription.cs
  Library/UserEntities/User.cs
  UserAPI/Data/Configurations/PasswordConfiguration.cs
  UserAPI/Data/Configurations/SubscriptionConfiguration.cs
  UserAPI/Data/Configurations/UserConfiguration.cs
  UserAPI/GlobalUsings.cs
  UserAPI/Profiles/SubscriptionProfile.cs
  UserAPI/Profiles/UserProfile.cs
  UserAPI/Services/UserService.cs
Labels: enhancement

#139 Implemented documentations for UsersController
  UserAPI/Controllers/UsersController.cs
Labels: documentation

#144 Feature/backend/order api/repository
  Library/OrderEntities/DeliveryType.cs
  Library/OrderEntities/Order.cs
  Library/OrderEntities/OrderStatus.cs
  OrderApi/Controllers/OrdersController.cs
  OrderApi/Data/Configurations/OrderConfiguration.cs
  OrderApi/Data/DataSeeder.cs
  OrderApi/Data/OrderDbContext.cs
  OrderApi/Models/Extensions/PaginatedResult.cs
  OrderApi/Models/Order.cs
  OrderApi/OrderApi.csproj
  OrderApi/Profiles/OrderProfile.cs
  OrderApi/Program.cs
  OrderApi/Repository/IRepository/IOrderRepository.cs
  OrderApi/Repository/OrderRepository.cs
  OrderApi/Services/IOrderService.cs
  OrderApi/Services/OrderService.cs
  OrderApi/appsettings.json
Labels: enhancement

#145 Feature/backend/library/deliverytype
  Library/OrderEntities/DeliveryType.cs
  Library/OrderEntities/Order.cs
Labels: enhancement

#143 Update issue templates
  .github/ISSUE_TEMPLATE/issue.md
Labels: documentation

#150 Fix/backend/user api/debug
  UserAPI/Controllers/UsersController.cs
  UserAPI/Models/Password.cs
  UserAPI/Models/RoleType.cs
  UserAPI/Models/Subscription.cs
  UserAPI/Models/User.cs
  UserAPI/Profiles/SubscriptionProfile.cs
  UserAPI/Profiles/UserProfile.cs
  UserAPI/Program.cs
  UserAPI/Repositories/SubscriptionRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/Services/SubscriptionService.cs
  UserAPI/Services/UserService.cs
  UserAPI/UserAPI.csproj
  UserAPI/appsettings.json
Labels: bug, enhancement

#152 Fix/backend/user api/debug subscription
  UserAPI/Program.cs
  UserAPI/Repositories/SubscriptionRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/Services/SubscriptionService.cs
  UserAPI/Services/UserService.cs
  UserAPI/UserAPI.csproj
Labels: bug, enhancement

#151 Create view of order for users and for manage panel
  Client/Views/Orders/AdminOrder.cshtml
  Client/Views/Orders/UserOrder.csthtml
Labels: enhancement

#160 Feature/backend/order-api/filter
  OrderApi/Controllers/OrdersController.cs
  OrderApi/Models/Extensions/OrderFilter.cs
  OrderApi/Repository/IRepository/IOrderRepository.cs
  OrderApi/Repository/OrderRepository.cs
  OrderApi/Services/IOrderService.cs
  OrderApi/Services/OrderService.cs
Labels: enhancement

#161 Feature/backend/order-api/program
  OrderApi/OrderApi.csproj
  OrderApi/Program.cs
Labels: enhancement

#158 Feature/frontend/client/user entities/view models
  Client/Client.csproj
  Client/Models/UserEntities/Password/ManageViewModel.cs
  Client/Models/UserEntities/Subscription/ManageViewModel.cs
  Client/Models/UserEntities/User/LoginViewModel.cs
  Client/Models/UserEntities/User/ManageViewModel.cs
  Client/Models/UserEntities/User/RegisterViewModel.cs
Labels: enhancement

#162 Added myself as codeowner
  .github/CODEOWNERS
Labels: enhancement

#163 Added SubscriptionController in backend
  UserAPI/Controllers/SubscriptionController.cs
Labels: enhancement

#164 Feature/frontend/client/views/subscription
  Client/Program.cs
  Client/Views/Subscription/Create.cshtml
  Client/Views/Subscription/Delete.cshtml
  Client/Views/Subscription/Edit.cshtml
  Client/Views/Subscription/Index.cshtml
  UserAPI/Controllers/SubscriptionMvcController.cs
  UserAPI/Models/SubscriptionViewModel.cs
Labels: enhancement

#168 Feature/frontend/client/user/controller/creation
  Client/Client.csproj
  Client/Controllers/HomeController.cs
  Client/Controllers/UsersController.cs
  Client/Models/ErrorViewModel.cs
  Client/Models/UserEntities/Password/ManagePasswordViewModel.cs
  Client/Models/UserEntities/Subscription/ManageSubscriptionViewModel.cs
  Client/Models/UserEntities/User/ManageUserViewModel.cs
  Client/Profiles/UserProfile.cs
  Client/Program.cs
  Client/Views/Home/Index.cshtml
  Client/Views/Home/Privacy.cshtml
  Library/Filters/UserFilter.cs
  UserAPI/Controllers/UsersController.cs
  UserAPI/GlobalUsings.cs
  UserAPI/Repositories/IUserRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/Services/IUserService.cs
  UserAPI/Services/UserService.cs
Labels: enhancement

#177 Feature/frontend/client/jwt auth
  Client/Client.csproj
  Client/Controllers/AuthController.cs
  Client/Models/Extensions/JwtSettings.cs
  Client/Models/Extensions/LoginRequest.cs
  Client/Program.cs
  Client/appsettings.json
Labels: enhancement

#181 Feature/backend/client/order-controller
  Client/Controllers/OrdersController.cs
  Client/Models/OrderEntities/DeliveryType/ManageDeliveryTypeViewModel.cs
  Client/Models/OrderEntities/Order/ManageOrderViewModel.cs
  Client/Profiles/DeliveryTypeProfile.cs
  Client/Profiles/OrderProfile.cs
  Client/Program.cs
  Gateway/ocelot.json
  Library/Filters/OrderFilter.cs
  OrderApi/Controllers/OrdersController.cs
  OrderApi/GlobalUsings.cs
  OrderApi/Repository/IRepository/IOrderRepository.cs
  OrderApi/Repository/OrderRepository.cs
  OrderApi/Services/IOrderService.cs
  OrderApi/Services/OrderService.cs
Labels: documentation, enhancement

#183 Feature/backend/user api/interface enhancement
  Library/Extensions/PaginatedResult.cs
  Library/Filters/OrderFilter.cs
  Library/Filters/UserFilter.cs
  Library/Interfaces/IManagable.cs
  UserAPI/Controllers/SubscriptionController.cs
  UserAPI/Repositories/ISubscriptionRepository.cs
  UserAPI/Repositories/IUserRepository.cs
  UserAPI/Repositories/SubscriptionRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/Services/ISubscriptionService.cs
  UserAPI/Services/IUserService.cs
  UserAPI/Services/SubscriptionService.cs
  UserAPI/Services/UserService.cs
Labels: documentation

#191 Feature/backend/book api/controller/search filter
  BookApi/Controllers/BooksController.cs
  BookApi/Services/BookService.cs
  BookApi/Services/IBookService.cs
Labels: enhancement

#193 Feature/backend/client/book controller
  BookApi/Data/BookDbContext.cs
  BookApi/Data/Configuration/AuthorConfiguration.cs
  BookApi/Data/Configuration/BookConfiguration.cs
  BookApi/Data/Configuration/CategoryConfiguration.cs
  BookApi/Data/Configuration/FeedbackConfiguration.cs
  BookApi/Data/Configuration/PublisherConfiguration.cs
  Client/Controllers/BookController.cs
  Client/Models/BookEntities/Book/ManageBookViewModel.cs
Labels: enhancement

#192 Feature/backend/user api/user/redis implementation
  UserAPI/Program.cs
  UserAPI/Repositories/IUserRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/UserAPI.csproj
Labels: documentation, enhancement

#196 Feature/backend/user api/user sorting
  Client/Controllers/UsersController.cs
  Library/Sortings/Bool.cs
  Library/Sortings/UserSort.cs
  UserAPI/Controllers/UsersController.cs
  UserAPI/GlobalUsings.cs
  UserAPI/Program.cs
  UserAPI/Repositories/IUserRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/Services/IUserService.cs
  UserAPI/Services/UserService.cs
Labels: documentation

#199 Fix/backend/library/directory change
  BookApi/GlobalUsings.cs
  BookApi/Profiles/AuthorProfile.cs
  BookApi/Profiles/BookProfile.cs
  BookApi/Profiles/CategoryProfile.cs
  BookApi/Services/AuthorService.cs
  BookApi/Services/BookService.cs
  BookApi/Services/CategoryService.cs
  BookApi/Services/IBookService.cs
  Client/Controllers/AuthController.cs
  Client/Controllers/BookController.cs
  Client/Controllers/DeliveryController.cs
  Client/Controllers/OrdersController.cs
  Client/Controllers/UsersController.cs
  Client/Models/BookEntities/Book/ManageBookViewModel.cs
  Client/Models/OrderEntities/Order/ManageOrderViewModel.cs
  Client/Models/UserEntities/User/ManageUserViewModel.cs
  Client/Profiles/DeliveryTypeProfile.cs
  Client/Profiles/OrderProfile.cs
  Client/Profiles/UserProfile.cs
  Library/DTOs/Book/Author.cs
  Library/DTOs/Book/Book.cs
  Library/DTOs/Book/Category.cs
  Library/DTOs/Book/CoverType.cs
  Library/DTOs/Book/Feedback.cs
  Library/DTOs/Book/Language.cs
  Library/DTOs/Book/Publisher.cs
  Library/DTOs/Order/DeliveryType.cs
  Library/DTOs/Order/Order.cs
  Library/DTOs/Order/OrderStatus.cs
  Library/DTOs/User/Basket.cs
  Library/DTOs/User/BasketItem.cs
  Library/DTOs/User/Password.cs
  Library/DTOs/User/RoleType.cs
  Library/DTOs/User/Subscription.cs
  Library/DTOs/User/User.cs
  Library/Filters/OrderFilter.cs
  Library/Filters/UserFilter.cs
  OrderApi/Controllers/StatusController.cs
  OrderApi/Data/DataSeeder.cs
  OrderApi/GlobalUsings.cs
  OrderApi/Models/Order.cs
  OrderApi/Profiles/OrderProfile.cs
  OrderApi/Repository/DeliveryTypeRepository.cs
  OrderApi/Repository/IRepository/IDeliveryTypeRepository.cs
  OrderApi/Services/DeliveryTypeService.cs
  UserAPI/Controllers/UsersController.cs
  UserAPI/Data/DataSeeder.cs
  UserAPI/Data/UserDbContext.cs
  UserAPI/GlobalUsings.cs
  UserAPI/Models/User.cs
  UserAPI/Profiles/SubscriptionProfile.cs
  UserAPI/Profiles/UserProfile.cs
  UserAPI/Repositories/IPasswordRepository.cs
  UserAPI/Repositories/PasswordRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/Services/PasswordService.cs
Labels: documentation

#201 Feature/backend/tests/creation
  Client/WebClient.csproj
  Gateway/GatewayAPI.csproj
  UserAPI.Tests/UserAPI.Tests.csproj
  book-store.sln
Labels: documentation, enhancement
