Repository zabavb/Libro, pull requests merged in 2025-04, with the labels that each got.

#524 Book and dicount in front-end
  client/src/api/adapters/bookAdapter.ts
  client/src/api/repositories/bookRepository.ts
  client/src/components/book/BookSort.tsx
  client/src/components/book/admin/BookAdminCard.tsx
  client/src/components/book/admin/BookAdminForm.tsx
  client/src/services/bookService.ts
  client/src/types/Filters/BookFilter.ts
  client/src/types/Sortings/BookSort.ts
  client/src/types/objects/Book.ts
  client/src/types/objects/BookView.ts
Labels: enhancement

#532 Feature/frontend/order-update
  Gateway/ocelot.json
  client/src/components/order/DeliveryList.tsx
  client/src/components/order/admin/DeliveryTypeForm.tsx
  client/src/components/order/admin/OrderForm.tsx
  client/src/components/order/admin/OrderFormBookSearch.tsx
  client/src/components/order/admin/OrderList.tsx
  client/src/components/user/UserCheckoutForm.tsx
  client/src/components/user/userOrderList/UserOrdersList.tsx
  client/src/containers/order/DeliveryTypeAdminCardContainer.tsx
  client/src/containers/order/DeliveryTypeFormContainer.tsx
  client/src/containers/order/DeliveryTypeListContainer.tsx
  client/src/containers/order/OrderAdminCardContainer.tsx
  client/src/containers/order/OrderCardContainer.tsx
  client/src/containers/order/OrderFormContainer.tsx
  client/src/containers/order/OrderListContainer.tsx
  client/src/containers/user/UserCheckoutFormContainer.tsx
  client/src/containers/user/UserOrdersListContainer.tsx
  client/src/pages/Admin/OrderRelated/Deliveries/DeliveriesListPage.tsx
  client/src/pages/Admin/OrderRelated/Deliveries/DeliveryFormPage.tsx
  client/src/services/deliveryTypeService.ts
  client/src/services/orderService.ts
  client/src/state/redux/index.ts
  client/src/state/redux/slices/deliveryTypeSlice.ts
  client/src/state/redux/store.ts
  client/src/utils/orderValidationSchema.ts
Labels: bug, enhancement

#533 Fix/backand/book api/redis db
  BookApi/Data/BookDbContext.cs
  BookApi/Data/CachHelper/CacheService.cs
  BookApi/Data/CachHelper/ICacheService.cs
  BookApi/Data/DataSeeder.cs
  BookApi/Models/Book.cs
  BookApi/Models/Feedback.cs
  BookApi/Program.cs
  BookApi/Repositories/AuthorRepository.cs
  BookApi/Repositories/BookRepository.cs
  BookApi/Repositories/CategoryRepository.cs
  BookApi/Repositories/FeedbackRepository.cs
  BookApi/Repositories/PublisherRepository.cs
  BookApi/Repositories/SubCategoryRepository.cs
  Library/DTOs/Book/Feedback.cs
Labels: bug, enhancement

#534 Update/backend/order api/merge functions
  BookApi/Controllers/FeedbacksController.cs
  BookApi/Models/Filters/FeedbackFilter.cs
  BookApi/Repositories/FeedbackRepository.cs
  BookApi/Repositories/Interfaces/IFeedbackRepository.cs
  BookApi/Services/FeedbackService.cs
  BookApi/Services/Interfaces/IFeedbackService.cs
  Library/DTOs/Order/Order.cs
  OrderApi/Repository/IOrderRepository.cs
  OrderApi/Repository/OrderRepository.cs
  OrderApi/Services/IOrderService.cs
  OrderApi/Services/OrderService.cs
Labels: enhancement

#530 Feature/frontend/books/main menu
  client/components.json
  client/package-lock.json
  client/package.json
  client/src/components/book/BookFilter.tsx
  client/src/components/layouts/CatalogMenu.tsx
  client/src/components/layouts/Footer.tsx
  client/src/components/layouts/Header.tsx
  client/src/components/layouts/MainLayout.tsx
  client/src/components/ui/dropdown-menu.tsx
  client/src/index.css
  client/src/lib/utils.ts
  client/tailwind.config.js
  client/tsconfig.app.json
  client/tsconfig.json
  client/vite.config.ts
Labels: enhancement

#539 Fix/backend/user api/merge functions
  BookApi/Repositories/BookRepository.cs
  BookApi/Services/FeedbackService.cs
  BookApi/Services/Interfaces/IFeedbackService.cs
  BookApi/appsettings.Development.json
  Gateway/.idea/.idea.Gateway.dir/.idea/workspace.xml
  Gateway/ocelot.json
  Library/Common/S3StorageService.cs
  Library/DTOs/UserRelated/Subscription/SubscriptionDto.cs
  OrderApi/Program.cs
  OrderApi/appsettings.Development.json
  UserAPI/Controllers/PasswordController.cs
  UserAPI/Controllers/SubscriptionsController.cs
  UserAPI/Controllers/UsersController.cs
  UserAPI/Data/Configurations/SubscriptionConfiguration.cs
  UserAPI/Data/Configurations/UserConfiguration.cs
  UserAPI/Data/DataSeeder.cs
  UserAPI/Data/UserDbContext.cs
  UserAPI/GlobalDefaults.cs
  UserAPI/Models/Password.cs
  UserAPI/Models/Subscription/SubscribeRequest.cs
  UserAPI/Models/Subscription/Subscription.cs
  UserAPI/Models/Subscription/UserSubscription.cs
  UserAPI/Models/User.cs
  UserAPI/Profiles/SubscriptionProfile.cs
  UserAPI/Profiles/UserProfile.cs
  UserAPI/Program.cs
  UserAPI/Repositories/Interfaces/ISubscriptionRepository.cs
  UserAPI/Repositories/SubscriptionRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/Services/Interfaces/IPasswordService.cs
  UserAPI/Services/Interfaces/ISubscriptionService.cs
  UserAPI/Services/PasswordService.cs
  UserAPI/Services/SubscriptionService.cs
  UserAPI/Services/UserService.cs
Labels: bug, documentation, enhancement

#535 Fix/backend/book api/model/author
  BookApi/Models/Author.cs
  Library/DTOs/Book/Author.cs
  client/src/components/book/admin/BookAdminCard.tsx
  client/src/components/book/admin/BookAdminForm.tsx
  client/src/utils/bookValidationSchema.ts
Labels: enhancement

#545 Feature/frontend/order-api/styles
  client/src/components/common/Pagination.tsx
  client/src/components/common/Search.tsx
  client/src/components/order/DeliveryList.tsx
  client/src/components/order/admin/DeliveryTypeAdminCard.tsx
  client/src/components/order/admin/OrderAdminCard.tsx
  client/src/components/order/admin/OrderForm.tsx
  client/src/components/order/admin/OrderFormBookSearch.tsx
  client/src/components/order/admin/OrderList.tsx
  client/src/containers/order/DeliveryTypeListContainer.tsx
  client/src/containers/order/OrderAdminCardContainer.tsx
  client/src/containers/order/OrderFormContainer.tsx
  client/src/containers/order/OrderListContainer.tsx
  client/src/pages/Admin/OrderRelated/Deliveries/DeliveriesListPage.tsx
  client/src/pages/Admin/OrderRelated/Orders/OrdersListPage.tsx
  client/src/styles/orderTableStyles.css
  client/src/styles/statusDisplay.css
Labels: bug, enhancement

#540 Feature/frontend/book-pages
  OrderApi/Program.cs
  client/src/api/repositories/bookRepository.ts
  client/src/api/repositories/orderRepository.ts
  client/src/components/book/BookCard.tsx
  client/src/components/book/BookCatalog.tsx
  client/src/components/book/BookDetails.tsx
  client/src/components/book/BookList.tsx
  client/src/components/book/admin/BookAdminCard.tsx
  client/src/components/user/UserCart.tsx
  client/src/containers/books/BookAdminCardContainer.tsx
  client/src/containers/books/BookCardContainer.tsx
  client/src/containers/books/BookCatalogContainer.tsx
  client/src/containers/books/BookDetailsContainer.tsx
  client/src/main.tsx
  client/src/pages/Admin/BookRelated/Books/BookDetailsPage.tsx
  client/src/pages/Main/MainPage.tsx
  client/src/pages/Main/book/AuthorsListPage.tsx
  client/src/pages/Main/book/BooksCatalogPage.tsx
  client/src/pages/Main/book/BooksListPage.tsx
  client/src/pages/Main/book/PublishersListPage.tsx
  client/src/pages/Main/user/SubscriptionPage.tsx
  client/src/pages/Main/user/UserCartPage.tsx
  client/src/pages/Main/user/UserCheckoutPage.tsx
  client/src/pages/Main/user/UserOrdersPage.tsx
  client/src/services/bookService.ts
  client/src/styles/bookCard.css
  client/src/types/Filters/BookFilter.ts
Labels: bug, enhancement

#546 added liked books
  client/src/components/book/BookCard.tsx
  client/src/pages/Main/BooksListPage.tsx
  client/src/pages/Main/likedBooksPage.ts
  client/src/services/bookService.ts
  client/src/services/likedBooksStorage.ts
Labels: enhancement

#549 Changed IsAvailable to Quantity in front and back ends
  BookApi/Controllers/BooksController.cs
  BookApi/Data/Configuration/BookConfiguration.cs
  BookApi/Data/DataSeeder.cs
  BookApi/Models/Book.cs
  BookApi/Models/Filters/BookFilter.cs
  BookApi/Repositories/BookRepository.cs
  BookApi/Repositories/Interfaces/IBookRepository.cs
  BookApi/Services/BookService.cs
  BookApi/Services/Interfaces/IBookService.cs
  DeadAspClient/Models/BookEntities/Book/ManageBookViewModel.cs
  DeadAspClient/Views/Books/Details.cshtml
  Library/DTOs/Book/Book.cs
  client/src/api/adapters/bookAdapter.ts
  client/src/components/book/admin/BookAdminCard.tsx
  client/src/components/book/admin/BookAdminForm.tsx
  client/src/types/objects/Book.ts
  client/src/types/objects/BookView.ts
  client/src/utils/bookValidationSchema.ts
Labels: enhancement

#553 Feature/frontend/styling
  BookApi/Repositories/BookRepository.cs
  OrderApi/Program.cs
  OrderApi/Repository/OrderRepository.cs
  client/package-lock.json
  client/package.json
  client/src/assets/logoLibro.svg
  client/src/assets/styles/base/status-display.css
  client/src/assets/styles/base/table-styles.css
  client/src/assets/styles/components/book-card.css
  client/src/assets/styles/components/delivery-list.css
  client/src/assets/styles/components/order-list.css
  client/src/assets/styles/components/pagination.css
  client/src/assets/styles/components/search-bar.css
  client/src/assets/styles/layout/admin-layout.css
  client/src/components/book/BookCard.tsx
  client/src/components/common/Pagination.tsx
  client/src/components/common/Search.tsx
  client/src/components/layouts/AdminLayout.tsx
  client/src/components/order/DeliveryList.tsx
  client/src/components/order/admin/DeliveryTypeAdminCard.tsx
  client/src/components/order/admin/OrderAdminCard.tsx
  client/src/components/order/admin/OrderList.tsx
  client/src/containers/order/DeliveryTypeAdminCardContainer.tsx
  client/src/routes.tsx
Labels: enhancement

#556 Feature/frontend/styling-details
  client/package-lock.json
  client/src/assets/styles/base/status-display.css
  client/src/assets/styles/base/table-styles.css
  client/src/assets/styles/components/delivery-list.css
  client/src/assets/styles/components/delivery/delivery-form.css
  client/src/assets/styles/components/list-styles.css
  client/src/assets/styles/components/order-list.css
  client/src/assets/styles/components/order/order-book-list.css
  client/src/assets/styles/components/order/order-book-search.css
  client/src/assets/styles/components/order/order-details.css
  client/src/assets/styles/components/order/order-form.css
  client/src/assets/styles/components/pagination.css
  client/src/assets/styles/components/search-bar.css
  client/src/assets/styles/layout/admin-layout.css
  client/src/components/order/OrderDetails.tsx
  client/src/components/order/OrderFormBookList.tsx
  client/src/components/order/admin/DeliveryList.tsx
  client/src/components/order/admin/DeliveryTypeForm.tsx
  client/src/components/order/admin/OrderAdminFormBookList.tsx
  client/src/components/order/admin/OrderForm.tsx
  client/src/components/order/admin/OrderFormBookList.tsx
  client/src/components/order/admin/OrderFormBookSearch.tsx
  client/src/components/order/admin/OrderList.tsx
  client/src/containers/order/DeliveryTypeListContainer.tsx
  client/src/containers/order/OrderDetailsContainer.tsx
  client/src/pages/Admin/OrderRelated/Deliveries/DeliveryFormPage.tsx
  client/src/pages/Admin/OrderRelated/Orders/OrderDetailsPage.tsx
  client/src/pages/Admin/OrderRelated/Orders/OrderFormPage.tsx
  client/src/routes.tsx
Labels: enhancement

#567 Refactor UI Components and Improve Styling with New Dependencies
  client/package-lock.json
  client/package.json
  client/src/assets/react.svg
  client/src/assets/styles/base/_colors.css
  client/src/assets/styles/layout/_header.css
  client/src/components/auth/Login.tsx
  client/src/components/auth/Register.tsx
  client/src/components/common/CarouselOffers.tsx
  client/src/components/common/DropDownList.tsx
  client/src/components/layouts/CatalogMenu.tsx
  client/src/components/layouts/Footer.tsx
  client/src/components/layouts/Header.tsx
  client/src/components/layouts/MainLayout.tsx
  client/src/index.css
  client/src/pages/Main/MainPage.tsx
  client/src/routes.tsx
  client/tailwind.config.js
Labels: enhancement

#578 Feature/backend/graphql/order/creation
  APIComposer/GraphQL/Queries/OrderQuery.cs
  APIComposer/GraphQL/Services/Interfaces/IOrderServiceClient.cs
  APIComposer/GraphQL/Services/OrderServiceClient.cs
  APIComposer/Program.cs
  BookApi/Controllers/BooksController.cs
  BookApi/Repositories/BookRepository.cs
  BookApi/Repositories/Interfaces/IBookRepository.cs
  BookApi/Services/BookService.cs
  BookApi/Services/Interfaces/IBookService.cs
  OrderApi/OrderFilter.cs
  OrderApi/OrderSort.cs
  OrderApi/Repository/Interfaces/IOrderRepository.cs
  OrderApi/Repository/OrderRepository.cs
  client/src/api/repositories/orderRepository.ts
  client/src/components/order/admin/OrderList.tsx
  client/src/containers/order/OrderListContainer.tsx
  client/src/pages/Main/MainPage.tsx
  client/src/services/orderService.ts
  client/src/types/Filters/OrderFilter.ts
  client/src/types/Sortings/OrderSort.ts
Labels: enhancement

#579 Fix/frontend/user/subscriptions
  .idea/.idea.book-store/.idea/dataSources.xml
  APIComposer/Properties/launchSettings.json
  BookApi/Services/BookService.cs
  Library/Common/S3StorageService.cs
  Library/DTOs/UserRelated/Subscription/SubscriptionDto.cs
  Library/Interfaces/IS3StorageService.cs
  Library/Library.csproj
  UserAPI/Controllers/SubscriptionsController.cs
  UserAPI/Data/Configurations/SubscriptionConfiguration.cs
  UserAPI/Data/UserDbContext.cs
  UserAPI/Profiles/SubscriptionProfile.cs
  UserAPI/Properties/launchSettings.json
  UserAPI/Repositories/SubscriptionRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/Services/SubscriptionService.cs
  UserAPI/Services/UserService.cs
  client/src/api/adapters/subscriptionAdapter.ts
  client/src/api/repositories/common.ts
  client/src/api/repositories/subscriptionRepository.ts
  client/src/api/repositories/userRepository.ts
  client/src/components/layouts/AdminLayout.tsx
  client/src/components/user/Subscription.tsx
  client/src/components/user/SubscriptionCard.tsx
  client/src/components/user/SubscriptionForm.tsx
  client/src/components/user/SubscriptionList.tsx
  client/src/containers/user/SubscriptionContainer.tsx
  client/src/containers/user/SubscriptionListContainer.tsx
  client/src/containers/user/UserListContainer.tsx
  client/src/main.tsx
  client/src/pages/Admin/UserRelated/Subscriptions/SubscriptionFormPage.tsx
  client/src/routes.tsx
  client/src/services/subscriptionService.ts
  client/src/services/userService.ts
  client/src/utils/subscriptionValidationSchema.ts
Labels: bug, documentation

#584 Feature/frontend/user/profile
  Gateway/ocelot.json
  OrderApi/Repository/OrderRepository.cs
  UserAPI.Tests/Services/PasswordServiceTests.cs
  UserAPI/Controllers/PasswordController.cs
  UserAPI/Repositories/Interfaces/IPasswordRepository.cs
  UserAPI/Repositories/PasswordRepository.cs
  UserAPI/Services/Interfaces/IPasswordService.cs
  UserAPI/Services/PasswordService.cs
  client/src/api/config/apiConfig.ts
  client/src/api/index.ts
  client/src/api/repositories/passwordRepository.ts
  client/src/components/layouts/AdminLayout.tsx
  client/src/components/layouts/Header.tsx
  client/src/components/user/Profile.tsx
  client/src/containers/common/ProfileContainer.tsx
  client/src/pages/common/ProfilePage.tsx
  client/src/pages/common/preferences/ChangePasswordPage.tsx
  client/src/pages/common/preferences/PreferencesPage.tsx
  client/src/routes.tsx
  client/src/services/passwordService.ts
  client/src/types/index.ts
  client/src/types/subTypes/ComplicatedLoading.ts
  client/src/utils/authValidationShema.ts
  client/src/utils/index.ts
  client/src/utils/userValidationSchema.ts
Labels: documentation, enhancement
