Repository zabavb/Libro, pull requests merged in 2025-02, with the labels that each got.

#317 Feature/frontend/user/validation
  client/package-lock.json
  client/package.json
  client/src/api/adapters/userAdapter.ts
  client/src/components/user/UserForm.tsx
  client/src/utils/index.ts
  client/src/utils/validationSchema.ts
Labels: enhancement

#325 Feature/frontend/user/search
  client/src/api/repositories/userRepository.ts
  client/src/components/common/Form.tsx
  client/src/components/common/List.tsx
  client/src/components/common/Pagination.tsx
  client/src/components/common/PaginationBox.tsx
  client/src/components/common/Search.tsx
  client/src/components/user/UserFilter.tsx
  client/src/components/user/UserList.tsx
  client/src/components/user/UserSort.tsx
  client/src/containers/user/UserListContainer.tsx
  client/src/state/redux/slices/userSlice.ts
  client/src/types/Filters/UserFilter.ts
  client/src/types/Sortings/UserSort.ts
  client/src/types/index.ts
  client/src/types/subObjects/Boolean.ts
  client/src/utils/index.ts
  client/src/utils/userValidationSchema.ts
Labels: enhancement

#326 Feature/backend/order-api/sorting
  Library/DTOs/Order/OrderStatus.cs
  OrderAPI.Tests/Controllers/OrdersControllersTest.cs
  OrderAPI.Tests/OrderApi.Tests.cs
  OrderAPI.Tests/Repositories/OrderRepositoryTests.cs
  OrderAPI.Tests/Services/OrderServiceTests.cs
  OrderApi/Controllers/OrdersController.cs
  OrderApi/Data/DataSeeder.cs
  OrderApi/GlobalUsings.cs
  OrderApi/OrderSort.cs
  OrderApi/Repository/IOrderRepository.cs
  OrderApi/Repository/OrderRepository.cs
  OrderApi/Services/IOrderService.cs
  OrderApi/Services/OrderService.cs
  book-store.sln
Labels: enhancement

#359 removed logging from statuscontroller
  OrderApi/Controllers/StatusController.cs
Labels: enhancement

#357 Feature/backend/order-api/data-annotations
  Library/DTOs/Order/DeliveryType.cs
  Library/DTOs/Order/Order.cs
  OrderAPI.Tests/Controllers/DeliveryTypesControllerTest.cs
  OrderAPI.Tests/Controllers/OrdersControllersTest.cs
  OrderAPI.Tests/Controllers/StatusControllerTest.cs
  OrderApi/Models/DeliveryType.cs
  OrderApi/Models/Order.cs
Labels: bug, enhancement

#376 Feature/backend/order-api/minor-update
  OrderAPI.Tests/Controllers/DeliveryTypesControllerTest.cs
  OrderAPI.Tests/Controllers/OrdersControllersTest.cs
  OrderApi/Controllers/DeliveryTypesController.cs
  OrderApi/Controllers/OrdersController.cs
  OrderApi/Controllers/StatusController.cs
  OrderApi/Program.cs
Labels: bug, enhancement

#377 Feature/frontend/order/admin
  client/src/api/adapters/orderAdapters.ts
  client/src/api/config/apiConfig.ts
  client/src/api/index.ts
  client/src/api/repositories/orderRepository.ts
  client/src/components/order/OrderFilter.tsx
  client/src/components/order/OrderList.tsx
  client/src/components/order/OrderSort.tsx
  client/src/components/order/admin/OrderAdminCard.tsx
  client/src/components/order/admin/OrderForm.tsx
  client/src/containers/order/OrderAdminCardContainer.tsx
  client/src/containers/order/OrderFormContainer.tsx
  client/src/containers/order/OrderListContainer.tsx
  client/src/pages/Admin/AdminPage.tsx
  client/src/pages/Admin/OrderRelated/Orders/OrderFormPage.tsx
  client/src/routes.tsx
  client/src/services/orderService.ts
  client/src/state/redux/index.ts
  client/src/state/redux/slices/orderSlice.ts
  client/src/state/redux/store.ts
  client/src/types/Filters/OrderFilter.ts
  client/src/types/Sortings/OrderSort.ts
  client/src/types/index.ts
  client/src/types/objects/Order.ts
  client/src/types/objects/OrderView.ts
  client/src/types/subTypes/Status.ts
  client/src/utils/index.ts
  client/src/utils/orderValidationSchema.ts
Labels: enhancement

#379 Feature/backend/user api/avatar
  .gitignore
  BookApi/Repositories/IAuthorRepository.cs
  BookApi/Repositories/IBookRepository.cs
  BookApi/Repositories/ICategoryRepository.cs
  BookApi/Repositories/IFeedbackRepository.cs
  BookApi/Repositories/IPublisherRepository.cs
  BookApi/Repositories/ISubCategoryRepository.cs
  Library/AWS/S3StorageService.cs
  Library/Common/PaginatedResult.cs
  Library/DTOs/User/User.cs
  Library/Interfaces/IManagable.cs
  Library/Interfaces/IS3StorageService.cs
  Library/Library.csproj
  OrderAPI.Tests/OrderAPI.Tests.csproj
  OrderApi/Properties/launchSettings.json
  OrderApi/Repository/IDeliveryTypeRepository.cs
  OrderApi/Repository/IOrderRepository.cs
  OrderApi/Services/IOrderService.cs
  UserAPI.Tests/Controllers/UsersControllerTest.cs
  UserAPI.Tests/Services/UserServiceTests.cs
  UserAPI/Controllers/UsersController.cs
  UserAPI/Models/User.cs
  UserAPI/Program.cs
  UserAPI/Repositories/ISubscriptionRepository.cs
  UserAPI/Repositories/IUserRepository.cs
  UserAPI/Services/ISubscriptionService.cs
  UserAPI/Services/IUserService.cs
  UserAPI/Services/UserService.cs
  UserAPI/UserAPI.csproj
  UserAPI/appsettings.Development.json
  UserAPI/appsettings.json
Labels: enhancement

#382 Feature/frontend/user/image/lazy loading
  Library/AWS/S3StorageService.cs
  UserAPI/Controllers/UsersController.cs
  UserAPI/Services/UserService.cs
  client/package-lock.json
  client/package.json
  client/src/api/adapters/userAdapter.ts
  client/src/api/repositories/userRepository.ts
  client/src/components/user/admin/UserAdminCard.tsx
  client/src/components/user/admin/UserForm.tsx
  client/src/containers/user/UserAdminCardContainer.tsx
  client/src/containers/user/UserFormContainer.tsx
  client/src/services/userService.ts
  client/src/state/redux/slices/userSlice.ts
  client/src/types/objects/User.ts
  client/src/types/objects/UserView.ts
  client/src/utils/userValidationSchema.ts
Labels: documentation, enhancement

#384 Feature/frontend/user/virtualization
  client/package-lock.json
  client/package.json
  client/src/components/user/UserCard.tsx
  client/src/components/user/UserForm.tsx
  client/src/components/user/UserList.tsx
  client/src/components/user/main/UserCard.tsx
  client/src/components/user/main/UserDetails.tsx
  client/src/containers/user/UserAdminCardContainer.tsx
  client/src/containers/user/UserCardContainer.tsx
  client/src/containers/user/UserFormContainer.tsx
Labels: documentation

#398 Feature/authentication
  Gateway/ocelot.json
  Library/DTOs/User/User.cs
  UserAPI/Controllers/AuthController.cs
  UserAPI/Controllers/UsersController.cs
  UserAPI/Models/Auth/RegisterRequest.cs
  UserAPI/Models/User.cs
  UserAPI/Services/AuthService.cs
  UserAPI/Services/IAuthService.cs
  client/src/api/config/apiConfig.ts
  client/src/api/index.ts
  client/src/components/auth/Login.tsx
  client/src/components/auth/Register.tsx
  client/src/components/order/admin/OrderAdminCard.tsx
  client/src/containers/auth/LoginContainer.tsx
  client/src/containers/auth/RegisterContainer.tsx
  client/src/privateRoute.tsx
  client/src/routes.tsx
  client/src/services/authService.ts
  client/src/services/index.ts
  client/src/state/context/AuthContext.tsx
  client/src/state/context/index.ts
  client/src/types/index.ts
  client/src/types/types/auth/login.ts
  client/src/types/types/auth/register.ts
  client/src/types/types/order/Order.ts
  client/src/types/types/order/OrderView.ts
  client/src/types/types/user/User.ts
  client/src/types/types/user/UserView.ts
  client/src/utils/authValidationShema.ts
  client/src/utils/index.ts
Labels: documentation, enhancement

#411 Feature/frontend/subscription
  client/src/pages/Admin/UserRelated/Subscriptions/SubscriptionDetailsPage.tsx
  client/src/pages/Admin/UserRelated/Subscriptions/SubscriptionFormPage.tsx
  client/src/pages/Admin/UserRelated/Subscriptions/SubscriptionsListPage.tsx
  client/src/pages/Main/SubscriptionPage.tsx
  client/src/routes.tsx
  client/src/services/subscriptionAutoRenewalService.ts
  client/src/services/subscriptionService.ts
  client/src/state/redux/slices/subscriptionSlice.ts
  client/src/types/types/order/Subscription.ts
  client/src/utils/subscriptionValidationSchema.ts
Labels: enhancement

#414 Features/book api/subcategories other fixes
  BookAPI.Tests/Controllers/AuthorsControllerTests.cs
  BookAPI.Tests/Controllers/FeedbacksControllerTests.cs
  BookAPI.Tests/Controllers/PublishersControllerTests.cs
  BookAPI.Tests/Repositories/AuthorRepositoryTests.cs
  BookAPI.Tests/Repositories/FeedbackRepositoryTests.cs
  BookAPI.Tests/Repositories/PublisherRepositoryTests.cs
  BookAPI.Tests/Services/AuthorServiceTests.cs
  BookAPI.Tests/Services/FeedbackServiceTests.cs
  BookAPI.Tests/Services/PublisherServiceTests.cs
  BookApi/BookApi.csproj
  BookApi/Data/Configuration/BookConfiguration.cs
  BookApi/Data/DataSeeder.cs
  BookApi/Models/Book.cs
  BookApi/Profiles/BookProfile.cs
  BookApi/Profiles/CategoryProfile.cs
  BookApi/Profiles/SubCategoryProfile.cs
  BookApi/Program.cs
  BookApi/Repositories/BookRepository.cs
  BookApi/Repositories/CategoryRepository.cs
  Library/DTOs/Book/Book.cs
Labels: enhancement

#403 Feature/frontend/order/delivery-admin
  OrderApi/Controllers/DeliveryTypesController.cs
  OrderApi/Services/IDeliveryTypeService.cs
  client/src/api/config/apiConfig.ts
  client/src/api/index.ts
  client/src/api/repositories/deliveryTypeRepository.ts
  client/src/components/order/DeliveryList.tsx
  client/src/components/order/admin/DeliveryTypeAdminCard.tsx
  client/src/components/order/admin/DeliveryTypeForm.tsx
  client/src/components/order/admin/OrderForm.tsx
  client/src/containers/order/DeliveryTypeAdminCardContainer.tsx
  client/src/containers/order/DeliveryTypeFormContainer.tsx
  client/src/containers/order/DeliveryTypeListContainer.tsx
  client/src/containers/order/OrderFormContainer.tsx
  client/src/pages/Admin/AdminPage.tsx
  client/src/pages/Admin/OrderRelated/Deliveries/DeliveryFormPage.tsx
  client/src/routes.tsx
  client/src/services/deliveryTypeService.ts
  client/src/services/index.ts
  client/src/state/redux/index.ts
  client/src/state/redux/slices/deliveryTypeSlice.ts
  client/src/state/redux/slices/orderSlice.ts
  client/src/state/redux/store.ts
  client/src/types/index.ts
  client/src/types/types/delivery/DeliveryType.ts
  client/src/utils/deliveryTypeValidationSchema.ts
  client/src/utils/index.ts
Labels: bug, enhancement
