Repository zabavb/Libro, pull requests merged in 2025-01, with the labels that each got.

#208 Feature/backend/tests/user api
  Client/Client.csproj
  Client/Views/Orders/AdminOrder.cshtml
  Client/Views/Orders/UserOrder.cshtml
  Client/Views/Shared/Error.cshtml
  Client/Views/Subscription/Create.cshtml
  Client/Views/Subscription/Delete.cshtml
  Client/Views/Subscription/Edit.cshtml
  Client/Views/Subscription/Index.cshtml
  Library/DTOs/Book/Author.cs
  Library/DTOs/Book/Book.cs
  Library/DTOs/Book/Category.cs
  Library/DTOs/Book/CoverType.cs
  Library/DTOs/Book/Feedback.cs
  Library/DTOs/Book/Language.cs
  Library/DTOs/Book/Publisher.cs
  Library/DTOs/Order/OrderStatus.cs
  Library/DTOs/User/User.cs
  Library/Interfaces/IManagable.cs
  UserAPI.Tests/UnitTests/Controllers/UsersControllerTest.cs
  UserAPI.Tests/UserAPI.Tests.csproj
  UserAPI/Controllers/BasketController.cs
  UserAPI/Controllers/SubscriptionController.cs
  UserAPI/Controllers/UsersController.cs
  UserAPI/Data/Configurations/SubscriptionConfiguration.cs
  UserAPI/Data/Configurations/UserConfiguration.cs
  UserAPI/Profiles/SubscriptionProfile.cs
  UserAPI/Profiles/UserProfile.cs
  UserAPI/Program.cs
  UserAPI/Properties/launchSettings.json
  UserAPI/Repositories/SubscriptionRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/Services/IUserService.cs
  UserAPI/Services/SubscriptionService.cs
  UserAPI/Services/UserService.cs
  UserAPI/UserAPI.csproj
Labels: enhancement

#210 Feature/backend/user api tests/structure
  UserAPI.Tests/IntegrationTests/Controllers/UsersControllerIntegrationTests.cs
  UserAPI.Tests/IntegrationTests/Services/UserServiceIntegrationTests.cs
  UserAPI.Tests/UnitTests/Repositories/UserRepositoryTests.cs
  UserAPI.Tests/UnitTests/Services/UserServiceTests.cs
  UserAPI.Tests/UserAPI.Tests.csproj
  UserAPI/Program.cs
  UserAPI/Repositories/UserRepository.cs
Labels: enhancement

#216 Feature/backend/order-api/redis
  OrderApi/Controllers/DeliveryTypesController.cs
  OrderApi/Controllers/OrdersController.cs
  OrderApi/Data/DataSeeder.cs
  OrderApi/OrderApi.csproj
  OrderApi/Program.cs
  OrderApi/Repository/DeliveryTypeRepository.cs
  OrderApi/Repository/IDeliveryTypeRepository.cs
  OrderApi/Repository/IOrderRepository.cs
  OrderApi/Repository/OrderRepository.cs
  OrderApi/Services/DeliveryTypeService.cs
  OrderApi/Services/OrderService.cs
Labels: documentation, enhancement

#217 Feature/backend/user api tests/unit/service
  BookApi/Profiles/AuthorProfile.cs
  BookApi/Profiles/BookProfile.cs
  BookApi/Profiles/CategoryProfile.cs
  BookApi/Services/AuthorService.cs
  BookApi/Services/BookService.cs
  BookApi/Services/CategoryService.cs
  UserAPI.Tests/UnitTests/Controllers/UsersControllerTest.cs
  UserAPI.Tests/UnitTests/Services/UserServiceTests.cs
  UserAPI.Tests/UserAPI.Tests.csproj
  UserAPI/Repositories/IUserRepository.cs
  UserAPI/Services/UserService.cs
Labels: documentation, enhancement

#215 Feature/backend/book api/controllers/additionalcontrollers
  BookApi/Controllers/FeedbacksController.cs
  BookApi/Controllers/PublishersController.cs
  BookApi/Models/Author.cs
  BookApi/Models/Book.cs
  BookApi/Models/Category.cs
  BookApi/Models/CoverType.cs
  BookApi/Models/Feedback.cs
  BookApi/Models/Language.cs
  BookApi/Models/Publisher.cs
  BookApi/Profiles/BookProfile.cs
  BookApi/Profiles/FeedbackProfile.cs
  BookApi/Profiles/PublisherProfile.cs
  BookApi/Program.cs
  BookApi/Services/FeedbackService.cs
  BookApi/Services/IFeedbackService.cs
  BookApi/Services/IPublisherService.cs
  BookApi/Services/PublisherService.cs
Labels: enhancement

#222 Feature/backend/library/controller-handlers
  Client/Controllers/DeliveryController.cs
  Client/Controllers/OrdersController.cs
  Client/Extensions/ErrorHandlers.cs
  Client/appsettings.json
Labels: bug, documentation, enhancement

#223 Feature/backend/book api/controllers/additionalcontrollers
  BookApi/Models/Author.cs
  BookApi/Models/Book.cs
  BookApi/Models/Category.cs
  BookApi/Models/CoverType.cs
  BookApi/Models/Feedback.cs
  BookApi/Models/Language.cs
  BookApi/Models/Publisher.cs
  BookApi/Profiles/AuthorProfile.cs
  BookApi/Profiles/BookProfile.cs
  BookApi/Profiles/CategoryProfile.cs
  BookApi/Profiles/FeedbackProfile.cs
  BookApi/Profiles/PublisherProfile.cs
  BookApi/Program.cs
  BookApi/Repositories/AuthorRepository.cs
  BookApi/Repositories/BookRepository.cs
  BookApi/Repositories/CategoryRepository.cs
  BookApi/Repositories/FeedbackRepository.cs
  BookApi/Repositories/IAuthorRepository.cs
  BookApi/Repositories/IBookRepository.cs
  BookApi/Repositories/ICategoryRepository.cs
  BookApi/Repositories/IFeedbackRepository.cs
  BookApi/Repositories/IPublisherRepository.cs
  BookApi/Repositories/PublisherRepository.cs
  BookApi/Services/AuthorService.cs
  BookApi/Services/BookService.cs
  BookApi/Services/CategoryService.cs
  BookApi/Services/FeedbackService.cs
  BookApi/Services/IBookService.cs
  BookApi/Services/PublisherService.cs
  BookApi/appsettings.json
Labels: documentation

#227 Feature/frontend/client/views/books
  Client/Views/Books/Details.cshtml
  Client/Views/Books/GetAllBooks.cshtml
  Client/Views/Books/Manage.cshtml
Labels: enhancement

#224 Fix/backend/user api/minor fixes
  Client/Controllers/UsersController.cs
  Client/Extensions/ErrorHandlers.cs
  Client/Models/UserEntities/User/LoginViewModel.cs
  Client/Models/UserEntities/User/ManageUserViewModel.cs
  Client/Models/UserEntities/User/RegisterViewModel.cs
  Client/Profiles/UserProfile.cs
  Client/appsettings.json
  Library/DTOs/User/User.cs
  Library/Extensions/PaginatedResult.cs
  Library/Sortings/UserSort.cs
  UserAPI.Tests/UnitTests/Repositories/UserRepositoryTests.cs
  UserAPI/Controllers/UsersController.cs
  UserAPI/Data/DataSeeder.cs
  UserAPI/Data/UserDbContext.cs
  UserAPI/GlobalSuppressions.cs
  UserAPI/Models/User.cs
  UserAPI/Repositories/IUserRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/Services/UserService.cs
Labels: documentation

#230 Feature/backend/book api/controllers/refactor
  BookApi/Controllers/BooksController.cs
  BookApi/Controllers/ReferenceDataController.cs
  BookApi/GlobalUsings.cs
  BookApi/Infrastructure/Extensions/BookFilterExtensions.cs
  BookApi/Infrastructure/Extensions/BookSearchExtensions.cs
  BookApi/Infrastructure/Extensions/BookSortExtensions.cs
  BookApi/Program.cs
  BookApi/Repositories/BookRepository.cs
  BookApi/Repositories/IBookRepository.cs
  BookApi/Services/BookService.cs
  BookApi/Services/CoverTypeService.cs
  BookApi/Services/IBookService.cs
  BookApi/Services/ICoverTypeService.cs
  BookApi/Services/ILanguageService.cs
  BookApi/Services/LanguageService.cs
  Library/Filters/BookFilter.cs
  Library/Sortings/BookSort.cs
Labels: enhancement

#237 Fix/backend/user api tests/integration/controller
  UserAPI.Tests/Controllers/UsersControllerTest.cs
  UserAPI.Tests/IntegrationTests/Controllers/UsersControllerIntegrationTests.cs
  UserAPI.Tests/IntegrationTests/Services/UserServiceIntegrationTests.cs
  UserAPI.Tests/Program.cs
  UserAPI.Tests/Repositories/UserRepositoryTests.cs
  UserAPI.Tests/Services/UserServiceTests.cs
  UserAPI.Tests/UserAPI.Tests.csproj
Labels: documentation, wontfix

#242 Created structure for frontend
  rn-client/src/api/index.js
  rn-client/src/api/userService.js
  rn-client/src/components/Button.js
  rn-client/src/contexts/AuthContext.js
  rn-client/src/navigation/AppNavigator.js
  rn-client/src/store/actions/authActions.js
  rn-client/src/store/reducers/authReducer.js
  rn-client/src/store/store.js
Labels: enhancement

#245 Implement logging
  BookApi/BookApi.csproj
  BookApi/Program.cs
Labels: enhancement

#246 Implement exceptions
  BookApi/Controllers/AuthorsController.cs
  BookApi/Controllers/BooksController.cs
  BookApi/Controllers/CategoriesController.cs
  BookApi/Controllers/FeedbacksController.cs
  BookApi/Controllers/PublishersController.cs
  BookApi/Controllers/ReferenceDataController.cs
Labels: enhancement

#262 Feature/backend/user api/jwt authentication
  Gateway/ocelot.json
  UserAPI/Controllers/AuthController.cs
  UserAPI/Models/Auth/IdentifierValidator.cs
  UserAPI/Models/Auth/JwtSettings.cs
  UserAPI/Models/Auth/LoginRequest.cs
  UserAPI/Models/Auth/RegisterRequest.cs
  UserAPI/Program.cs
  UserAPI/Repositories/AuthRepository.cs
  UserAPI/Repositories/IAuthRepository.cs
  UserAPI/Services/AuthService.cs
  UserAPI/Services/IAuthService.cs
  UserAPI/UserAPI.csproj
  UserAPI/appsettings.json
  rn-client/.gitignore
  rn-client/App.js
  rn-client/app.json
  rn-client/assets/adaptive-icon.png
  rn-client/assets/favicon.png
  rn-client/assets/icon.png
  rn-client/assets/splash-icon.png
  rn-client/package-lock.json
  rn-client/package.json
  rn-client/src/api/index.js
  rn-client/src/api/userService.js
  rn-client/src/components/Button.js
  rn-client/src/contexts/AuthContext.js
  rn-client/src/navigation/AppNavigator.js
  rn-client/src/store/actions/authActions.js
  rn-client/src/store/reducers/authReducer.js
  rn-client/src/store/store.js
Labels: enhancement

#274 Fix/frontend/user/crud operations debug
  client/index.html
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/App.tsx
  client/src/components/user/UserCard.tsx
  client/src/components/user/UserList.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/main.tsx
  client/src/pages/Admin/AdminPage.tsx
  client/src/pages/Admin/UserRelated/Users/UsersListPage.tsx
  client/src/pages/Main/MainPage.tsx
  client/src/pages/Main/NotFoundPage.tsx
  client/src/routes.tsx
  client/tailwind.config.js
  client/vite.config.ts
Labels: enhancement

#281 Delete .github/ISSUE_TEMPLATE directory
  .github/ISSUE_TEMPLATE/issue.md
Labels: invalid

#288 Refactor SubCategory
  BookApi/Controllers/SubCategoriesController.cs
  BookApi/Repositories/ISubCategoryRepository.cs
  BookApi/Repositories/SubCategoryRepository.cs
  BookApi/Services/ISubCategoryService.cs
  BookApi/Services/SubCategoryService.cs
  book-store.sln
Labels: documentation, enhancement

#293 Feature/backend/order api/catching-up
  OrderApi/Controllers/DeliveryTypesController.cs
  OrderApi/Controllers/OrdersController.cs
  OrderApi/Controllers/StatusController.cs
  OrderApi/Data/Configurations/OrderConfiguration.cs
  OrderApi/Data/OrderDbContext.cs
  OrderApi/Models/DeliveryType.cs
  OrderApi/Models/Order.cs
  OrderApi/Profiles/DeliveryTypeProfile.cs
  OrderApi/Profiles/OrderProfile.cs
  OrderApi/Program.cs
  OrderApi/Repository/DeliveryTypeRepository.cs
  OrderApi/Repository/OrderRepository.cs
  OrderApi/Services/DeliveryTypeService.cs
  OrderApi/Services/IOrderService.cs
  OrderApi/Services/OrderService.cs
  book-store.sln
Labels: documentation, enhancement

#298 added logging and commenting
  UserAPI/Controllers/SubscriptionController.cs
Labels: documentation, enhancement

#300 added tests of order.api controllers
  OrderAPI.Tests/Controllers/DeliveryTypesControllerTest.cs
  OrderAPI.Tests/Controllers/OrdersControllersTest.cs
  OrderAPI.Tests/Controllers/StatusControllerTest.cs
  OrderAPI.Tests/OrderApi.Tests.cs
Labels: documentation, enhancement

#301 refactored password-service
  UserAPI/Services/PasswordService.cs
Labels: documentation, enhancement

#305 Fix/backend/book api/smallfixes
  BookApi/BookApi.csproj
  BookApi/Data/Configuration/CategoryConfiguration.cs
  BookApi/Data/Configuration/SubcategoryConfiguration.cs
  BookApi/Program.cs
Labels: documentation

#310 Fix of mocking mismatch
  UserAPI.Tests/Services/UserServiceTests.cs
Labels: documentation

#313 Feature/backend/order-api/tests
  OrderAPI.Tests/OrderAPI.Tests.csproj
  OrderAPI.Tests/Repositories/DeliveryTypeRepositoryTests.cs
  OrderAPI.Tests/Repositories/OrderRepositoryTests.cs
  OrderAPI.Tests/Services/DeliveryTypeServiceTests.cs
  OrderAPI.Tests/Services/OrderServiceTests.cs
  OrderApi/Data/Configurations/DeliveryTypeConfiguration.cs
  OrderApi/Data/Configurations/OrderConfiguration.cs
  OrderApi/Data/OrderDbContext.cs
  OrderApi/Models/DeliveryType.cs
  OrderApi/Models/Order.cs
  OrderApi/Profiles/OrderProfile.cs
  OrderApi/Repository/DeliveryTypeRepository.cs
  OrderApi/Repository/OrderRepository.cs
  OrderApi/Services/DeliveryTypeService.cs
  OrderApi/Services/OrderService.cs
  book-store.sln
Labels: documentation, enhancement

#315 Features/backend/book api/tests
  BookAPI.Tests/BookAPI.Tests.csproj
  BookAPI.Tests/Controllers/PublishersControllerTests.cs
  BookAPI.Tests/Repositories/PublisherRepositoryTests.cs
  BookAPI.Tests/Services/PublisherServiceTests.cs
  BookApi/Controllers/PublishersController.cs
  BookApi/Data/BookDbContext.cs
  BookApi/Repositories/PublisherRepository.cs
  BookApi/Services/PublisherService.cs
  UserAPI.Tests/Services/UserServiceTests.cs
  book-store.sln
Labels: documentation, enhancement
