Repository zabavb/Libro, pull requests merged in 2025-03, with the labels that each got.

#420 Fix/frontend/router
  client/src/api/config/apiConfig.ts
  client/src/routes.tsx
Labels: bug

#422 Feature/frontend/order/book support
  client/src/components/order/admin/OrderForm.tsx
  client/src/components/order/admin/OrderFormBookList.tsx
  client/src/components/order/admin/OrderFormBookSearch.tsx
  client/src/containers/order/DeliveryTypeListContainer.tsx
  client/src/containers/order/OrderFormContainer.tsx
  client/src/types/index.ts
Labels: bug, enhancement

#418 Feature/backend/user api/password controller
  DeadAspClient/Controllers/UsersController.cs
  UserAPI.Tests/Controllers/PasswordControllerTests.cs
  UserAPI.Tests/Repositories/PasswordRepositoryTests.cs
  UserAPI.Tests/Services/PasswordServiceTests.cs
  UserAPI/Controllers/PasswordController.cs
  UserAPI/Repositories/IPasswordRepository.cs
  UserAPI/Repositories/PasswordRepository.cs
  UserAPI/Services/IPasswordService.cs
  UserAPI/Services/PasswordService.cs
  UserAPI/Services/UserService.cs
  testfile.txt
  testfile.txt.asc
Labels: documentation

#427 Feature/backend/order api/amount
  Library/DTOs/Order/Order.cs
  OrderApi/Data/Configurations/OrderConfiguration.cs
  OrderApi/Data/DataSeeder.cs
  OrderApi/Models/Order.cs
  OrderApi/Repository/OrderRepository.cs
  client/src/api/adapters/orderAdapters.ts
  client/src/components/order/admin/OrderAdminCard.tsx
  client/src/components/order/admin/OrderForm.tsx
  client/src/components/order/admin/OrderFormBookList.tsx
  client/src/types/types/order/Order.ts
  client/src/types/types/order/OrderView.ts
  client/src/utils/orderValidationSchema.ts
Labels: enhancement

#428 Feature/backend/order-api/delivery-update
  OrderApi/Controllers/DeliveryTypesController.cs
  OrderApi/DeliverySort.cs
  OrderApi/Repository/DeliveryTypeRepository.cs
  OrderApi/Repository/IDeliveryTypeRepository.cs
  OrderApi/Services/DeliveryTypeService.cs
  OrderApi/Services/IDeliveryTypeService.cs
  client/src/api/repositories/deliveryTypeRepository.ts
  client/src/components/order/DeliveryList.tsx
  client/src/components/order/DeliverySort.tsx
  client/src/components/order/admin/OrderForm.tsx
  client/src/containers/order/DeliveryTypeListContainer.tsx
  client/src/services/deliveryTypeService.ts
  client/src/state/redux/slices/deliveryTypeSlice.ts
  client/src/types/Sortings/DeliverySort.ts
  client/src/types/index.ts
Labels: bug, enhancement

#435 Fix/gateway usage minor fixes
  Gateway/Program.cs
  Gateway/ocelot.json
  UserAPI/Controllers/UsersController.cs
  UserAPI/Data/DataSeeder.cs
  UserAPI/Data/UserDbContext.cs
  UserAPI/GlobalUsings.cs
  UserAPI/Models/Filters/UserFilter.cs
  UserAPI/Program.cs
  UserAPI/Repositories/IPasswordRepository.cs
  UserAPI/Repositories/PasswordRepository.cs
  UserAPI/Services/AuthService.cs
  client/src/api/config/apiConfig.ts
Labels: bug

#436 Feature/frontend/prettier formatter
  client/.prettierrc
  client/package-lock.json
  client/package.json
Labels: documentation

#437 Feature/auth/creation#2
  Gateway/Program.cs
  UserAPI/Controllers/AuthController.cs
  UserAPI/Program.cs
  UserAPI/Services/AuthService.cs
  client/src/components/auth/Login.tsx
  client/src/components/auth/Register.tsx
  client/src/components/book/BookFilter.tsx
  client/src/containers/auth/LoginContainer.tsx
  client/src/containers/auth/RegisterContainer.tsx
  client/src/pages/Admin/UserRelated/Users/UserFormPage.tsx
  client/src/pages/Admin/UserRelated/Users/UsersListPage.tsx
  client/src/pages/Auth/LoginPage.tsx
  client/src/pages/Auth/RegisterPage.tsx
  client/src/pages/Main/NotFoundPage.tsx
  client/src/pages/User/Preferences/PreferencesPage.tsx
  client/src/pages/common/BasketPage.tsx
  client/src/pages/common/ForbiddenPage.tsx
  client/src/pages/common/NotFoundPage.tsx
  client/src/pages/common/Orders/OrderFormPage.tsx
  client/src/pages/common/Orders/OrdersListPage.tsx
  client/src/pages/common/ProfilePage.tsx
  client/src/pages/common/preferences/ChangePasswordPage.tsx
  client/src/pages/common/preferences/PreferencesPage.tsx
  client/src/routes.tsx
  client/src/services/authService.ts
  client/src/state/context/AuthContext.tsx
  client/src/types/index.ts
  client/src/types/subTypes/Notification.ts
  client/src/types/types/auth/JwtResponse.tsx
  client/src/types/types/auth/login.ts
  client/src/types/types/auth/register.ts
  client/src/utils/authValidationShema.ts
Labels: bug, documentation

#441 Removed loggers for static functions to avoid initializing error
  UserAPI/Data/DataSeeder.cs
  UserAPI/Repositories/PasswordRepository.cs
Labels: bug

#467 DON'T MERGE YET Features/backend/book api/images audio support
  BookApi/Controllers/BooksController.cs
  BookApi/Controllers/FilesController.cs
  BookApi/Data/BookDbContext.cs
  BookApi/Data/DataSeeder.cs
  BookApi/Models/Book.cs
  BookApi/Program.cs
  BookApi/Repositories/BookRepository.cs
  BookApi/Services/BookService.cs
  BookApi/Services/Interfaces/IBookService.cs
  Library/AWS/S3StorageService.cs
  Library/DTOs/Book/Book.cs
Labels: enhancement, question

#476 Bugfix/backend/bookapi
  Gateway/ocelot.json
  client/src/api/config/apiConfig.ts
Labels: bug

#481 Feature/auth/oauth/creation
  Gateway/ocelot.json
  UserAPI.Tests/Controllers/PasswordControllerTests.cs
  UserAPI.Tests/Controllers/UsersControllerTest.cs
  UserAPI/Controllers/AuthController.cs
  UserAPI/Controllers/PasswordController.cs
  UserAPI/Controllers/SubscriptionController.cs
  UserAPI/Controllers/UsersController.cs
  UserAPI/Data/Configurations/UserConfiguration.cs
  UserAPI/Models/Auth/JwtSettings.cs
  UserAPI/Models/Auth/LoginRequest.cs
  UserAPI/Models/Auth/OAuthRequest.cs
  UserAPI/Models/Auth/RegisterRequest.cs
  UserAPI/Program.cs
  UserAPI/Repositories/AuthRepository.cs
  UserAPI/Repositories/Interfaces/IAuthRepository.cs
  UserAPI/Repositories/Interfaces/IPasswordRepository.cs
  UserAPI/Repositories/Interfaces/ISubscriptionRepository.cs
  UserAPI/Repositories/Interfaces/IUserRepository.cs
  UserAPI/Repositories/PasswordRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/Services/AuthService.cs
  UserAPI/Services/Interfaces/IAuthService.cs
  UserAPI/Services/Interfaces/IPasswordService.cs
  UserAPI/Services/Interfaces/ISubscriptionService.cs
  UserAPI/Services/Interfaces/IUserService.cs
  UserAPI/Services/PasswordService.cs
  UserAPI/Services/SubscriptionService.cs
  UserAPI/Services/UserService.cs
  UserAPI/UserAPI.csproj
  UserAPI/appsettings.json
  book-store.sln
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/api/config/apiConfig.ts
  client/src/api/index.ts
  client/src/api/repositories/common.ts
  client/src/api/repositories/userRepository.ts
  client/src/components/auth/Login.tsx
  client/src/components/auth/Register.tsx
  client/src/components/user/UserList.tsx
  client/src/containers/auth/LoginContainer.tsx
  client/src/containers/auth/RegisterContainer.tsx
  client/src/containers/user/UserListContainer.tsx
  client/src/pages/Admin/UserRelated/Users/UsersListPage.tsx
  client/src/pages/Auth/RegisterPage.tsx
  client/src/services/authService.ts
  client/src/services/index.ts
  client/src/state/context/AuthContext.tsx
  client/vite.config.ts
Labels: bug, documentation, enhancement

#482 Feature/frontend/user orders
  OrderApi/OrderFilter.cs
  OrderApi/Repository/OrderRepository.cs
  client/src/components/order/OrderCard.tsx
  client/src/components/user/userOrderList/UserOrdersList.tsx
  client/src/components/user/userOrderList/UserOrdersListFilter.tsx
  client/src/components/user/userOrderList/UserOrdersListSort.tsx
  client/src/containers/order/OrderCardContainer.tsx
  client/src/containers/user/UserOrdersListContainer.tsx
  client/src/pages/Main/UserOrdersPage.tsx
  client/src/routes.tsx
  client/src/types/Filters/OrderFilter.ts
Labels: enhancement

#487 Fix/basket rename
  client/src/components/user/UserCart.tsx
  client/src/components/user/UserCheckoutForm.tsx
  client/src/containers/user/UserCheckoutFormContainer.tsx
  client/src/pages/Main/MainPage.tsx
  client/src/pages/Main/UserCartPage.tsx
  client/src/pages/Main/UserCheckoutPage.tsx
  client/src/routes.tsx
  client/src/state/context/useBasket.tsx
  client/src/state/context/useCart.tsx
  client/src/types/types/cart/CartItem.ts
  client/src/utils/orderValidationSchema.ts
Labels: bug, enhancement

#490 Feature/frontend/orders-admin-panel-update
  client/src/components/order/admin/OrderForm.tsx
  client/src/components/order/admin/OrderList.tsx
  client/src/containers/order/OrderFormContainer.tsx
  client/src/containers/order/OrderListContainer.tsx
  client/src/pages/Admin/OrderRelated/Orders/OrdersListPage.tsx
  client/src/routes.tsx
Labels: enhancement

#508 Feature/frontend/user/marge enitites avatars
  Library/AWS/S3StorageService.cs
  Library/Interfaces/IS3StorageService.cs
  UserAPI/Models/Filters/UserFilter.cs
  UserAPI/Services/UserService.cs
  client/src/api/adapters/userAdapter.ts
  client/src/api/repositories/userRepository.ts
  client/src/components/auth/Register.tsx
  client/src/components/user/UserCard.tsx
  client/src/components/user/UserForm.tsx
  client/src/components/user/UserList.tsx
  client/src/containers/user/UserCardContainer.tsx
  client/src/containers/user/UserFormContainer.tsx
  client/src/containers/user/UserListContainer.tsx
  client/src/services/userService.ts
  client/src/state/redux/index.ts
  client/src/state/redux/slices/userSlice.ts
  client/src/state/redux/store.ts
  client/src/types/Filters/UserFilter.ts
  client/src/types/Sortings/UserSort.ts
  client/src/types/index.ts
  client/src/types/subTypes/Role.ts
  client/src/types/subTypes/ServiceResponse.ts
  client/src/types/subTypes/user/EmailDomen.ts
  client/src/types/subTypes/user/Role.ts
  client/src/types/types/user/User.ts
  client/src/types/types/user/UserCard.ts
  client/src/types/types/user/UserForm.ts
  client/src/types/types/user/UserView.ts
  client/src/utils/userValidationSchema.ts
Labels: bug, documentation

#505 Fix/merge-update
  BookApi/Data/Configuration/BookConfiguration.cs
  BookApi/Data/DataSeeder.cs
  BookApi/Models/Book.cs
  BookApi/Repositories/Interfaces/IAuthorRepository.cs
  BookApi/Repositories/Interfaces/IBookRepository.cs
  BookApi/Repositories/Interfaces/ICategoryRepository.cs
  BookApi/Repositories/Interfaces/IFeedbackRepository.cs
  BookApi/Repositories/Interfaces/IPublisherRepository.cs
  BookApi/Repositories/Interfaces/ISubCategoryRepository.cs
  BookApi/Services/BookService.cs
  BookApi/appsettings.json
  Library/AWS/S3StorageService.cs
  OrderApi/GlobalUsings.cs
  OrderApi/Repository/IDeliveryTypeRepository.cs
  OrderApi/Repository/IOrderRepository.cs
  OrderApi/Services/IDeliveryTypeService.cs
  OrderApi/Services/IOrderService.cs
Labels: bug

#515 Feature/backend/user-mergefunctions
  BookApi/Controllers/FilesController.cs
  BookApi/Data/DataSeeder.cs
  BookApi/GlobalConstants.cs
  BookApi/Repositories/AuthorRepository.cs
  BookApi/Repositories/BookRepository.cs
  BookApi/Repositories/CategoryRepository.cs
  BookApi/Repositories/FeedbackRepository.cs
  BookApi/Repositories/PublisherRepository.cs
  BookApi/Repositories/SubCategoryRepository.cs
  BookApi/Services/BookService.cs
  BookApi/appsettings.json
  OrderApi/OrderApi.csproj
  OrderApi/Program.cs
  OrderApi/Repository/IOrderRepository.cs
  OrderApi/Repository/OrderRepository.cs
  OrderApi/appsettings.json
Labels: bug, enhancement

#517 Featuare/backend/user api/user/advanced exception handling
  BookApi/BookApi.csproj
  BookApi/Controllers/FilesController.cs
  BookApi/Data/BookDbContext.cs
  BookApi/Data/DataSeeder.cs
  BookApi/Program.cs
  BookApi/Services/BookService.cs
  Library/Common/Middleware/ErrorResponse.cs
  Library/Common/Middleware/ExceptionMiddleware.cs
  Library/Common/Middleware/MiddlewareExtensions.cs
  Library/Common/Middleware/RepositoryException.cs
  Library/Common/S3StorageService.cs
  Library/Library.csproj
  UserAPI/Controllers/AuthController.cs
  UserAPI/Controllers/UsersController.cs
  UserAPI/Program.cs
  UserAPI/Repositories/AuthRepository.cs
  UserAPI/Repositories/UserRepository.cs
  UserAPI/Services/AuthService.cs
  UserAPI/Services/AvatarService.cs
  UserAPI/Services/UserService.cs
Labels: documentation

#519 Fix/backand/book api/get feedbacks by user
  BookApi/Controllers/FeedbacksController.cs
  BookApi/Data/BookDbContext.cs
  BookApi/Data/DataSeeder.cs
  BookApi/Models/Feedback.cs
  BookApi/Program.cs
  BookApi/Repositories/CategoryRepository.cs
  BookApi/Repositories/FeedbackRepository.cs
  BookApi/Repositories/Interfaces/IFeedbackRepository.cs
  BookApi/Services/FeedbackService.cs
  BookApi/Services/Interfaces/IFeedbackService.cs
  Library/DTOs/Book/Feedback.cs
Labels: bug, enhancement
