Repository zabavb/Libro, pull requests merged in 2025-05, with the labels that each got.

#589 Feature/backend/user api/data seeder
  Library/DTOs/UserRelated/Subscription/SubscriptionCardDto.cs
  Library/DTOs/UserRelated/Subscription/SubscriptionDto.cs
  Library/DTOs/UserRelated/User/UserDetails.cs
  UserAPI/Data/Configurations/SubscriptionConfiguration.cs
  UserAPI/Data/DataSeeder.cs
  UserAPI/Data/SeedImages/Subscriptions/image_0.png
  UserAPI/Data/UserDbContext.cs
  UserAPI/GlobalDefaults.cs
  UserAPI/Models/Password.cs
  UserAPI/Models/PasswordExtensions.cs
  UserAPI/Models/Subscription/Subscription.cs
  UserAPI/Models/Subscription/UserSubscription.cs
  UserAPI/Models/User.cs
  UserAPI/Program.cs
  UserAPI/Repositories/PasswordRepository.cs
  UserAPI/Services/AvatarService.cs
  UserAPI/Services/Interfaces/IAvatarService.cs
  UserAPI/Services/SubscriptionService.cs
  UserAPI/Services/UserService.cs
  UserAPI/UserAPI.csproj
  client/src/components/user/Profile.tsx
  client/src/components/user/SubscriptionCard.tsx
  client/src/components/user/SubscriptionForm.tsx
  client/src/services/userService.ts
  client/src/types/types/user/Subscription.ts
  client/src/types/types/user/SubscriptionCard.ts
  client/src/utils/subscriptionValidationSchema.ts
Labels: bug, documentation, enhancement

#591 Feature/frontend/details-styling
  client/src/assets/fonts/Gilroy-Medium.ttf
  client/src/assets/icons/ratingStar.svg
  client/src/assets/icons/truckIcon.svg
  client/src/assets/styles/components/book/book-details.css
  client/src/components/book/BookCard.tsx
  client/src/components/book/BookDetails.tsx
  client/src/components/book/FeedbackCard.tsx
  client/src/index.css
  client/src/pages/Main/book/BookDetailsPage.tsx
  client/src/routes.tsx
Labels: enhancement

#594 Feature/frontend/header panels styling
  client/src/api/adapters/bookAdapter.ts
  client/src/assets/MasterCard.svg
  client/src/assets/Visa.svg
  client/src/assets/icons/cartBig.svg
  client/src/assets/icons/hamburgerIcon.svg
  client/src/assets/icons/headerHeart.svg
  client/src/assets/icons/headerUser.svg
  client/src/assets/icons/magnifyingGlass.svg
  client/src/assets/icons/menuClose.svg
  client/src/assets/icons/socialFacebook.svg
  client/src/assets/icons/socialInstagram.svg
  client/src/assets/icons/socialTelegram.svg
  client/src/assets/icons/userBonus.svg
  client/src/assets/icons/userBookmark.svg
  client/src/assets/icons/userLogout.svg
  client/src/assets/icons/userSettings.svg
  client/src/assets/icons/userTruck.svg
  client/src/assets/styles/base/_colors.css
  client/src/assets/styles/components/book/catalog-filter.css
  client/src/assets/styles/components/book/catalog.css
  client/src/assets/styles/components/common/cart-card.css
  client/src/assets/styles/layout/_footer.css
  client/src/assets/styles/layout/_header.css
  client/src/assets/styles/layout/cart-panel.css
  client/src/assets/styles/layout/user-panel.css
  client/src/components/book/BookCard.tsx
  client/src/components/book/BookCatalog.tsx
  client/src/components/common/CartCard.tsx
  client/src/components/common/DropdownWrapper.tsx
  client/src/components/layouts/AdminLayout.tsx
  client/src/components/layouts/CartPanel.tsx
  client/src/components/layouts/CatalogMenu.tsx
  client/src/components/layouts/Footer.tsx
  client/src/components/layouts/Header.tsx
  client/src/components/layouts/UserPanel.tsx
  client/src/lib/icons.ts
  client/src/pages/Main/book/BooksCatalogPage.tsx
  client/src/state/context/useCart.tsx
  client/src/utils/storage.ts
Labels: bug, enhancement

#600 Fix/backend/graphql/connection
  APIComposer/GraphQL/Queries/OrderQuery.cs
  APIComposer/Program.cs
  BookApi/Data/DataSeeder.cs
  BookApi/Models/Book.cs
  BookApi/Models/CoverType.cs
  BookApi/Models/Filters/BookFilter.cs
  BookApi/Models/Language.cs
  BookApi/Services/CoverTypeService.cs
  BookApi/Services/LanguageService.cs
  Library/DTOs/Book/CoverType.cs
  Library/DTOs/Book/Language.cs
  client/src/assets/styles/layout/_footer.css
Labels: bug

#598 Feature/frontend/order-styling
  client/src/assets/icons/bArrowRight.svg
  client/src/assets/icons/bMoney.svg
  client/src/assets/icons/bPen.svg
  client/src/assets/styles/components/common/cart-checkout-card.css
  client/src/assets/styles/components/order/checkout-confirmation.css
  client/src/assets/styles/components/order/checkout-form.css
  client/src/assets/styles/components/order/order-success.css
  client/src/components/common/CartCard.tsx
  client/src/components/common/CartCheckoutCard.tsx
  client/src/components/common/CheckoutBookCard.tsx
  client/src/components/common/CheckoutListing.tsx
  client/src/components/layouts/CartPanel.tsx
  client/src/components/layouts/Header.tsx
  client/src/components/order/OrderCheckoutForm.tsx
  client/src/components/order/OrderConfirmation.tsx
  client/src/components/user/UserCheckoutForm.tsx
  client/src/containers/order/OrderCheckoutFormContainer.tsx
  client/src/containers/order/OrderConfirmationContainer.tsx
  client/src/lib/icons.ts
  client/src/pages/Main/book/BookDetailsPage.tsx
  client/src/pages/Main/order/OrderCheckoutPage.tsx
  client/src/pages/Main/order/OrderConfirmationPage.tsx
  client/src/pages/Main/order/OrderSuccessPage.tsx
  client/src/pages/Main/user/UserCheckoutPage.tsx
  client/src/routes.tsx
  client/src/utils/orderValidationSchema.ts
Labels: bug, enhancement

#603 Feature/front end/user-admin-styling
  client/src/assets/icons/bPlus.svg
  client/src/assets/icons/oArrowLeft.svg
  client/src/assets/icons/oTrash.svg
  client/src/assets/icons/wPen.svg
  client/src/assets/styles/base/table-styles.css
  client/src/assets/styles/components/list-styles.css
  client/src/assets/styles/components/pagination.css
  client/src/assets/styles/components/search-bar.css
  client/src/assets/styles/components/user/user-filter.css
  client/src/assets/styles/components/user/user-form.css
  client/src/assets/styles/layout/auth-panel.css
  client/src/components/common/Pagination.tsx
  client/src/components/common/Search.tsx
  client/src/components/layouts/AdminLayout.tsx
  client/src/components/layouts/AuthPanel.tsx
  client/src/components/order/admin/DeliveryList.tsx
  client/src/components/order/admin/DeliveryTypeAdminCard.tsx
  client/src/components/order/admin/OrderAdminCard.tsx
  client/src/components/order/admin/OrderList.tsx
  client/src/components/user/SubscriptionDropdown.tsx
  client/src/components/user/UserCard.tsx
  client/src/components/user/UserFilter.tsx
  client/src/components/user/UserForm.tsx
  client/src/components/user/UserList.tsx
  client/src/components/user/UserSort.tsx
  client/src/containers/auth/AuthPanelContainer.tsx
  client/src/containers/auth/LoginContainer.tsx
  client/src/containers/user/UserFormContainer.tsx
  client/src/containers/user/UserListContainer.tsx
  client/src/lib/icons.ts
  client/src/pages/Admin/UserRelated/Users/UserFormPage.tsx
  client/src/types/subTypes/user/Role.ts
Labels: bug, enhancement

#613 Bugfix/frontend/cart
  client/src/components/layouts/CartPanel.tsx
  client/src/components/order/OrderCheckoutForm.tsx
  client/src/components/order/OrderConfirmation.tsx
  client/src/components/user/UserCart.tsx
  client/src/containers/books/BookCardContainer.tsx
  client/src/containers/books/BookDetailsContainer.tsx
  client/src/containers/order/OrderCheckoutFormContainer.tsx
  client/src/containers/order/OrderConfirmationContainer.tsx
  client/src/pages/Main/order/OrderConfirmationPage.tsx
  client/src/routes.tsx
  client/src/state/context/CartContext.tsx
  client/src/state/context/useCart.tsx
Labels: bug

#614 Feature/frontend/user-order-list
  client/src/assets/link.svg
  client/src/assets/styles/components/order/order-card.css
  client/src/assets/styles/components/user/user-orders-filter.css
  client/src/assets/styles/components/user/user-orders-list.css
  client/src/components/order/OrderCard.tsx
  client/src/components/user/userOrderList/UserOrdersList.tsx
  client/src/components/user/userOrderList/UserOrdersListFilter.tsx
  client/src/containers/user/UserOrdersListContainer.tsx
  client/src/pages/Main/user/UserOrdersPage.tsx
Labels: enhancement

#615 Feature/frontend/category admin
  client/src/api/adapters/bookAdapter.ts
  client/src/api/config/apiConfig.ts
  client/src/api/index.ts
  client/src/api/repositories/categoryRepository.ts
  client/src/api/repositories/subcategoryRepository.ts
  client/src/assets/styles/components/book/sub-category-list.css
  client/src/assets/styles/components/common/subCategoryDropdown.css
  client/src/assets/styles/components/list-styles.css
  client/src/assets/styles/layout/_footer.css
  client/src/components/book/admin/CategoryForm.tsx
  client/src/components/book/admin/CategoryList.tsx
  client/src/components/book/admin/SubCategoryForm.tsx
  client/src/components/book/admin/SubCategoryList.tsx
  client/src/components/common/SubCategoryDropdownWrapper.tsx
  client/src/containers/books/CategoryFormContainer.tsx
  client/src/containers/books/CategoryListContainer.tsx
  client/src/containers/books/SubCategoryFormContainer.tsx
  client/src/containers/books/SubCategoryListContainer.tsx
  client/src/pages/Admin/BookRelated/Categories/CategoriesListPage.tsx
  client/src/pages/Admin/BookRelated/Categories/CategoryFormPage.tsx
  client/src/pages/Admin/BookRelated/Categories/SubCategoryFormPage.tsx
  client/src/routes.tsx
  client/src/services/categoryService.ts
  client/src/services/deliveryTypeService.ts
  client/src/services/index.ts
  client/src/services/subCategoryService.ts
  client/src/types/Filters/SubCategoryFilter.ts
  client/src/types/Sortings/SubCategorySort.ts
  client/src/types/index.ts
  client/src/types/subTypes/PaginatedResponse.ts
  client/src/types/types/book/Category.ts
  client/src/types/types/book/SubCategory.ts
  client/src/utils/categoryValidationSchema.ts
  client/src/utils/index.ts
  client/src/utils/subCategoryValidationSchema.ts
Labels: bug, enhancement

#618 Bugfix/order api
  UserAPI/Data/DataSeeder.cs
  UserAPI/Program.cs
  UserAPI/Services/UserService.cs
  client/src/api/adapters/bookAdapter.ts
  client/src/assets/styles/components/book/book-details.css
  client/src/assets/styles/components/book/card.css
  client/src/assets/styles/components/book/catalog-filter.css
  client/src/assets/styles/components/book/catalog.css
  client/src/assets/styles/components/common/profile.css
  client/src/assets/styles/components/list-styles.css
  client/src/assets/styles/components/order/checkout-confirmation.css
  client/src/assets/styles/components/user/user-form.css
  client/src/assets/styles/layout/user-panel.css
  client/src/components/book/BookCard.tsx
  client/src/components/book/admin/AuthorAdminCard.tsx
  client/src/components/common/CartCard.tsx
  client/src/components/layouts/CartPanel.tsx
  client/src/routes.tsx
  client/src/types/objects/Book.ts
  client/src/types/objects/BookView.ts
  client/src/types/types/book/Author.ts
Labels: bug

#622 Feature/frontend/book-admin
  BookApi/Controllers/BooksController.cs
  BookApi/Services/BookService.cs
  Library/Common/Search.cs
  Library/DTOs/Book/Book.cs
  Library/DTOs/Book/UpdateBookRequest.cs
  client/src/api/adapters/bookAdapter.ts
  client/src/api/repositories/bookRepository.ts
  client/src/assets/styles/components/book/author-search.css
  client/src/assets/styles/components/book/book-form.css
  client/src/assets/styles/components/order/order-form.css
  client/src/components/book/BookFormAuthorSearch.tsx
  client/src/components/book/BookFormPublisherSearch.tsx
  client/src/components/book/BookList.tsx
  client/src/components/book/admin/BookAdminCard.tsx
  client/src/components/book/admin/BookAdminForm.tsx
  client/src/components/book/admin/BookForm.tsx
  client/src/components/layouts/UserPanel.tsx
  client/src/containers/books/BookAdminCardContainer.tsx
  client/src/containers/books/BookFormContainer.tsx
  client/src/containers/books/BookListContainer.tsx
  client/src/pages/Admin/BookRelated/Books/BookFormPage.tsx
  client/src/routes.tsx
  client/src/services/bookService.ts
  client/src/types/objects/Book.ts
  client/src/types/subTypes/Book/CoverType.ts
  client/src/types/subTypes/Book/Language.ts
  client/src/utils/bookValidationSchema.ts
Labels: bug, enhancement

#623 Feature/frontend/book admin finish
  client/src/api/repositories/bookRepository.ts
  client/src/assets/icons/oCross.svg
  client/src/components/book/BookFormCategorySearch.tsx
  client/src/components/book/BookFormSubcategorySearch.tsx
  client/src/components/book/BookSubcategoryList.tsx
  client/src/components/book/admin/BookForm.tsx
  client/src/lib/icons.ts
  client/src/services/subCategoryService.ts
  client/src/utils/bookValidationSchema.ts
Labels: bug, enhancement

#626 Feature/frontend/extra-styling
  BookApi/Controllers/AuthorsController.cs
  BookApi/Controllers/SubCategoriesController.cs
  BookApi/Models/Filters/BookFilter.cs
  client/src/api/repositories/authorRepository.ts
  client/src/api/repositories/publisherRepository.ts
  client/src/assets/styles/components/book/book-details.css
  client/src/assets/styles/components/book/card.css
  client/src/assets/styles/components/book/catalog-sort.css
  client/src/assets/styles/layout/cart-panel.css
  client/src/components/book/BookCard.tsx
  client/src/components/book/BookCatalog.tsx
  client/src/components/book/BookDetails.tsx
  client/src/components/book/BookSort.tsx
  client/src/components/book/CatalogFilter.tsx
  client/src/components/book/CatalogSort.tsx
  client/src/components/common/AuthorFilters.tsx
  client/src/components/common/AuthorList.tsx
  client/src/components/common/CategoryFilters.tsx
  client/src/components/common/DropdownWrapper.tsx
  client/src/components/common/PublisherFilters.tsx
  client/src/components/common/RangeSlider.tsx
  client/src/components/common/SubcategoryFilters.tsx
  client/src/components/layouts/CartPanel.tsx
  client/src/components/layouts/Header.tsx
  client/src/containers/books/BookCardContainer.tsx
  client/src/containers/books/BookCatalogContainer.tsx
  client/src/containers/books/BookDetailsContainer.tsx
  client/src/types/Filters/BookFilter.ts
  client/src/types/Sortings/BookSort.ts
Labels: bug, enhancement

#630 Feature/frontend/author update
  BookApi/Controllers/AuthorsController.cs
  BookApi/GlobalUsings.cs
  BookApi/Profiles/AuthorProfile.cs
  BookApi/Services/AuthorService.cs
  BookApi/Services/Interfaces/IAuthorService.cs
  Library/DTOs/Book/AuthorRequest.cs
  client/src/api/repositories/authorRepository.ts
  client/src/components/book/BookList.tsx
  client/src/components/book/admin/AuthorAdminCard.tsx
  client/src/components/book/admin/AuthorForm.tsx
  client/src/components/book/admin/AuthorList.tsx
  client/src/components/book/admin/BookForm.tsx
  client/src/components/book/admin/CategoryList.tsx
  client/src/components/book/admin/FeedbackList.tsx
  client/src/components/book/admin/PublisherList.tsx
  client/src/components/layouts/UserPanel.tsx
  client/src/components/order/admin/DeliveryList.tsx
  client/src/components/order/admin/OrderList.tsx
  client/src/components/user/UserList.tsx
  client/src/containers/books/AuthorFormContainer.tsx
  client/src/containers/books/BookFormContainer.tsx
  client/src/pages/Admin/AdminPage.tsx
  client/src/services/authorService.ts
  client/src/services/bookService.ts
  client/src/utils/authorValidationSchema.ts
Labels: bug, enhancement

#631 Fix/backend/book categories
  BookApi/Controllers/AuthorsController.cs
  BookApi/Controllers/BooksController.cs
  BookApi/Data/CachHelper/CacheService.cs
  BookApi/Data/DataSeeder.cs
  BookApi/Repositories/BookRepository.cs
  BookApi/Repositories/CategoryRepository.cs
  BookApi/Repositories/SubCategoryRepository.cs
  BookApi/Services/BookService.cs
  BookApi/Services/CategoryService.cs
  BookApi/Services/SubCategoryService.cs
  Library/DTOs/Book/UpdateBookRequest.cs
Labels: bug, enhancement

#634 Minor-fix, due to incorrect conflict fix
  BookApi/Controllers/AuthorsController.cs
Labels: bug
